#!/system/bin/sh

sleep 40

if [ -e /sys/module/lowmemorykiller/parameters/adj ];
then
   echo "0,58,117,176,529,1000" > /sys/module/lowmemorykiller/parameters/adj
fi;

if [ -e /sys/module/lowmemorykiller/parameters/minfree ];
then
   echo "12288,15360,18432,21504,24576,30720" > /sys/module/lowmemorykiller/parameters/minfree
fi;
